In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

In [3]:
dataset=pd.read_csv("reduced_dataset.csv")

In [4]:
dataset

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0     55  112656       92393          581             113               2   
1     56   91569      131575          641              54               1   
2     26   78169       75417          569             105               3   
3     26   63033       10804          326             118               1   
4     24   29665       21182          662             102               3   
..   ...     ...         ...          ...             ...             ...   
995   21   35959      200465          310               1               3   
996   32   57400       68970          574              39               2   
997   38   47736      200653          705              54               2   
998   18   93942      202636          820             107               4   
999   67   29180      218027          703             109               1   

     InterestRate  LoanTerm  DTIRatio    Education EmploymentType  \
0           23.54        36      0.15          PhD  Self-employed   
1           15.19        12      0.43  High School      Part-time   
2           18.02        12      0.29     Master's      Part-time   
3           14.71        24      0.41  High School      Part-time   
4           15.02        60      0.69          PhD     Unemployed   
..            ...       ...       ...          ...            ...   
995         23.76        48      0.47          PhD      Full-time   
996         16.47        60      0.87     Master's     Unemployed   
997         12.44        48      0.47     Master's  Self-employed   
998         13.04        48      0.66     Master's  Self-employed   
999          4.26        60      0.75          PhD      Full-time   

    MaritalStatus HasMortgage HasDependents LoanPurpose HasCoSigner  Default  
0          Single         Yes           Yes        Home          No        0  
1        Divorced         Yes           Yes   Education         Yes        0  
2         Married         Yes           Yes   Education         Yes        0  
3          Single          No            No    Business         Yes        0  
4          Single          No           Yes    Business         Yes        0  
..            ...         ...           ...         ...         ...      ...  
995        Single         Yes           Yes        Home          No        1  
996      Divorced         Yes           Yes       Other          No        0  
997       Married         Yes           Yes    Business          No        1  
998        Single         Yes           Yes        Auto         Yes        0  
999      Divorced         Yes           Yes   Education         Yes        0  

[1000 rows x 17 columns]

In [5]:
print(dataset.columns.tolist())

['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default']


In [6]:
from sklearn.preprocessing import LabelEncoder

# Copy dataframe
dataset = dataset.copy()

# Columns to encode
categorical_cols = ['Education',
  'EmploymentType',
  'MaritalStatus',
  'HasMortgage',
  'HasDependents',
  'LoanPurpose',
  'HasCoSigner'
]

# Apply LabelEncoder
le = LabelEncoder()
for col in categorical_cols:
    dataset[col] = le.fit_transform(dataset[col].astype(str))

In [7]:
dataset[col]

0      0
1      1
2      1
3      1
4      1
      ..
995    0
996    0
997    0
998    1
999    1
Name: HasCoSigner, Length: 1000, dtype: int32

In [8]:
dataset = dataset.drop(columns=["LoanID"], errors="ignore")

In [9]:
dataset

Age  Income  LoanAmount  CreditScore  MonthsEmployed  NumCreditLines  \
0     55  112656       92393          581             113               2   
1     56   91569      131575          641              54               1   
2     26   78169       75417          569             105               3   
3     26   63033       10804          326             118               1   
4     24   29665       21182          662             102               3   
..   ...     ...         ...          ...             ...             ...   
995   21   35959      200465          310               1               3   
996   32   57400       68970          574              39               2   
997   38   47736      200653          705              54               2   
998   18   93942      202636          820             107               4   
999   67   29180      218027          703             109               1   

     InterestRate  LoanTerm  DTIRatio  Education  EmploymentType  \
0           23.54        36      0.15          3               2   
1           15.19        12      0.43          1               1   
2           18.02        12      0.29          2               1   
3           14.71        24      0.41          1               1   
4           15.02        60      0.69          3               3   
..            ...       ...       ...        ...             ...   
995         23.76        48      0.47          3               0   
996         16.47        60      0.87          2               3   
997         12.44        48      0.47          2               2   
998         13.04        48      0.66          2               2   
999          4.26        60      0.75          3               0   

     MaritalStatus  HasMortgage  HasDependents  LoanPurpose  HasCoSigner  \
0                2            1              1            3            0   
1                0            1              1            2            1   
2                1            1              1            2            1   
3                2            0              0            1            1   
4                2            0              1            1            1   
..             ...          ...            ...          ...          ...   
995              2            1              1            3            0   
996              0            1              1            4            0   
997              1            1              1            1            0   
998              2            1              1            0            1   
999              0            1              1            2            1   

     Default  
0          0  
1          0  
2          0  
3          0  
4          0  
..       ...  
995        1  
996        0  
997        1  
998        0  
999        0  

[1000 rows x 17 columns]

In [10]:
dataset.columns

Index(['Age', 'Income', 'LoanAmount', 'CreditScore', 'MonthsEmployed',
       'NumCreditLines', 'InterestRate', 'LoanTerm', 'DTIRatio', 'Education',
       'EmploymentType', 'MaritalStatus', 'HasMortgage', 'HasDependents',
       'LoanPurpose', 'HasCoSigner', 'Default'],
      dtype='object')

In [11]:
independent=dataset[['Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner']]

In [12]:
dependent=dataset[['Default']]

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(independent,dependent,test_size=1/3,random_state=0)

In [14]:
#SVM Classification
from sklearn.svm import SVC
classifier=SVC(kernel='rbf', random_state=0)
classifier=classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test,y_predict)
print(cm)
print(cl_report)

[[303   0]
 [ 31   0]]
              precision    recall  f1-score   support

           0       0.91      1.00      0.95       303
           1       0.00      0.00      0.00        31

    accuracy                           0.91       334
   macro avg       0.45      0.50      0.48       334
weighted avg       0.82      0.91      0.86       334



In [15]:
#Decision Tree Classification
from sklearn.tree import DecisionTreeClassifier
classifier=DecisionTreeClassifier(criterion= 'entropy', random_state=0)
classifier.fit(X_train,y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test,y_predict)
print(cm)
print(cl_report)

[[263  40]
 [ 24   7]]
              precision    recall  f1-score   support

           0       0.92      0.87      0.89       303
           1       0.15      0.23      0.18        31

    accuracy                           0.81       334
   macro avg       0.53      0.55      0.54       334
weighted avg       0.85      0.81      0.83       334



In [16]:
#KNN Classification
from sklearn.neighbors import KNeighborsClassifier
classifier=KNeighborsClassifier(n_neighbors=7, metric='minkowski',p=2)
classifier.fit(X_train, y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test,y_predict)
print(cm)
print(cl_report)

[[299   4]
 [ 31   0]]
              precision    recall  f1-score   support

           0       0.91      0.99      0.94       303
           1       0.00      0.00      0.00        31

    accuracy                           0.90       334
   macro avg       0.45      0.49      0.47       334
weighted avg       0.82      0.90      0.86       334



In [17]:
#Naive Bayes Classification
from sklearn.naive_bayes import GaussianNB
classifier=GaussianNB()
classifier.fit(X_train, y_train)
y_predict=classifier.predict(X_test)
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test, y_predict)
from sklearn.metrics import classification_report
cl_report=classification_report(y_test, y_predict)
print(cl_report)
print(cm)

              precision    recall  f1-score   support

           0       0.91      0.99      0.95       303
           1       0.00      0.00      0.00        31

    accuracy                           0.90       334
   macro avg       0.45      0.50      0.47       334
weighted avg       0.82      0.90      0.86       334

[[301   2]
 [ 31   0]]
